export const Informations = {
  WHO: "https://www.who.int/",
  "Ukraine": "https://moz.gov.ua/",
  "USA" : "https://www.hhs.gov/",
  "Italy" : "http://www.salute.gov.it/portale/home.html",
  "Spain" : "https://www.mscbs.gob.es/en/directoa/home.htm",
  "Germany" : "https://www.bundesgesundheitsministerium.de/",
  "Iran" : "https://behdasht.gov.ir/",
  "France" : "https://solidarites-sante.gouv.fr/",
  "UK" : "https://www.gov.uk/government/organisations/department-of-health-and-social-care",
  "Switzerland" : "http://www.euro.who.int/en/countries/switzerland",
  "Belgium" : "https://www.health.belgium.be/en",
  "Netherlands" : "https://www.government.nl/ministries/ministry-of-health-welfare-and-sport",
  "Turkey" : "https://www.saglik.gov.tr/",
  "Austria" : "https://www.sozialministerium.at/",
  "S. Korea" : "http://www.mohw.go.kr/react/index.jsp",
  "Canada" : "https://www.canada.ca/en/health-canada.html",
  "Portugal" : "https://www.portugal.gov.pt/en/gc21/ministries/health",
  "Israel" : "https://www.health.gov.il/English/Pages/HomePage.aspx",
  "Brazil" : "http://www.saude.gov.br/",
  "Norway" : "https://www.regjeringen.no/en/dep/hod/id421/",
  "Australia" : "https://www.health.gov.au/",
  "Sweden" : "https://www.government.se/government-of-sweden/ministry-of-health-and-social-affairs/",
  "Czechia" : "http://www.mzcr.cz/",
  "Ireland" : "https://www.gov.ie/en/organisation/department-of-health/",
  "Denmark" : "http://sum.dk/",
  "Malaysia" : "http://www.moh.gov.my/index.php",
  "Chile" : "https://www.gob.cl/en/ministries/ministry-of-health/",
  "Russia" : "http://government.ru/department/23/events/",
  "Romania" : "http://www.ms.ro/",
  "Poland" : "http://www.mz.gov.pl/",
  "Philippines" : "https://www.doh.gov.ph/",
  "Luxembourg" : "https://msan.gouvernement.lu/en.html",
  "Ecuador" : "https://www.salud.gob.ec/",
  "Japan" : "https://www.mhlw.go.jp/english/",
  "Pakistan" : "http://www.nhsrc.gov.pk/",
  "Thailand" : "http://www.moph.go.th/",
  "Saudi Arabia" : "https://www.moh.gov.sa/en/Pages/default.aspx",
  "Indonesia" : "http://www.kemkes.go.id/",
  "Finland" : "https://stm.fi/en/frontpage",
  "South Africa" : "http://www.health.gov.za/",
  "India" : "https://www.mohfw.gov.in/",
  "Greece" : "https://www.moh.gov.gr/",
  "Iceland" : "https://www.government.is/ministries/ministry-of-health/",
  "Dominican Republic" : "https://www.msp.gob.do/web/",
  "Mexico" : "https://www.gob.mx/salud/en",
  "Panama" : "http://www.minsa.gob.pa/",
  "Argentina" : "https://www.argentina.gob.ar/salud",
  "Peru" : "https://www.gob.pe/minsa/",
  "Singapore" : "https://www.moh.gov.sg/",
  "Serbia" : "https://www.zdravlje.gov.rs/",
  "Croatia" : "https://zdravstvo.gov.hr/",
  "Slovenia" : "https://www.gov.si/en/state-authorities/ministries/ministry-of-health/",
  "Colombia" : "http://www.minsalud.gov.co/",
  "Estonia" : "https://www.sm.ee/en",
  "Hong Kong" : "http://www.moh.gov.cn/",
  "Diamond Princess" : null,
  "Qatar" : "https://www.moph.gov.qa/english/Pages/default.aspx",
  "UAE" : "https://www.mohap.gov.ae/en/Pages/default.aspx",
  "Egypt" : "http://www.mohp.gov.eg/",
  "New Zealand" : "https://www.health.govt.nz/",
  "Iraq" : "http://www.moh.gov.iq/",
  "Algeria" : "http://www.ands.dz/",
  "Morocco" : "https://www.sante.gov.ma/Pages/Accueil.aspx",
  "Bahrain" : "https://www.moh.gov.bh/?lang=en",
  "Lithuania" : "http://sam.lrv.lt/",
  "Armenia" : "http://www.moh.am/",
  "Hungary" : "https://www.kormany.hu/en/ministry-of-human-resources",
  "Lebanon" : "https://www.moph.gov.lb/en",
  "Bosnia and Herzegovina" : "http://www.fbihvlada.gov.ba/english/ministarstva/zdravstvo.php",
  "Bulgaria" : "http://www.mh.government.bg/en/",
  "Latvia" : "http://www.vm.gov.lv/en/",
  "Andorra" : "https://www.salut.ad/",
  "Slovakia" : "http://www.uvzsr.sk/en/",
  "Tunisia" : "http://www.santetunisie.rns.tn/",
  "Moldova" : "https://msmps.gov.md/en",
  "Kazakhstan" : "http://www.mz.gov.kz/",
  "Costa Rica" : "https://www.ministeriodesalud.go.cr/",
  "North Macedonia" : "http://zdravstvo.gov.mk/",
  "Taiwan" : "https://www.mohw.gov.tw/mp-2.html",
  "Uruguay" : "https://www.gub.uy/ministerio-salud-publica/",
  "Azerbaijan" : "http://www.sehiyye.gov.az/",
  "Kuwait" : "https://www.moh.gov.kw/",
  "Jordan" : "https://www.moh.gov.jo/",
  "Cyprus" : "https://www.moh.gov.cy/moh/moh.nsf/index_en/index_en",
  "Réunion" : "http://www.health.gov.sc/index.php/tag/reunion-island/",
  "Burkina Faso" : "https://www.sante.gov.bf/",
  "Albania" : "https://shendetesia.gov.al/",
  "San Marino" : "http://www.sanita.sm/on-line/home.html",
  "Vietnam" : "http://moh.gov.vn/",
  "Cameroon" : "https://www.minsante.cm/",
  "Oman" : "https://www.moh.gov.om/",
  "Cuba" : "http://www.sld.cu/",
  "Senegal" : "http://www.sante.gouv.sn/",
  "Afghanistan" : "https://moph.gov.af/",
  "Faeroe Islands" : "https://www.hmr.fo/en/",
  "Malta" : "https://deputyprimeminister.gov.mt/en/Pages/health.aspx",
  "Ivory Coast" : "http://www.sante.gouv.ci/",
  "Uzbekistan" : "https://www.minzdrav.uz/",
  "Ghana" : "https://www.moh.gov.gh/",
  "Belarus" : "http://minzdrav.gov.by/",
  "Mauritius" : "http://health.govmu.org/",
  "Sri Lanka" : "http://www.health.gov.lk/",
  "Honduras" : "http://www.salud.gob.hn/",
  "Channel Islands" : "https://solidarites-sante.gouv.fr/",
  "Venezuela" : "http://www.mpps.gob.ve/",
  "Nigeria" : "http://www.health.gov.ng/",
  "Brunei" : "http://www.moh.gov.bn/Pages/Home.aspx",
  "Martinique" : "https://solidarites-sante.gouv.fr/",
  "Palestine" : "http://www.moh.gov.ps/",
  "Georgia" : "https://www.moh.gov.ge/",
  "Cambodia" : "http://moh.gov.kh/",
  "Bolivia" : "https://www.minsalud.gob.bo/",
  "Kyrgyzstan" : "http://www.med.kg/ru/",
  "Turkmenistan" : "http://www.saglykhm.gov.tm/",
  "Guadeloupe" : "https://solidarites-sante.gouv.fr/",
  "Montenegro" : "http://www.mzd.gov.me/ministarstvo",
  "DRC" : "http://www.minisanterdc.cd/",
  "Mayotte" : "https://solidarites-sante.gouv.fr/",
  "Trinidad and Tobago" : "http://www.health.gov.tt/",
  "Rwanda" : "https://moh.gov.rw/",
  "Gibraltar" : "https://www.gha.gi/about-us/ministry-for-health/",
  "Paraguay" : "https://www.mspbs.gov.py/index.php",
  "Liechtenstein" : "https://www.regierung.li/ministries/ministry-of-social-affairs/",
  "Isle of Man" : "https://www.gov.im/about-the-government/departments/health-and-social-care/",
  "Kenya" : "http://www.health.go.ke/",
  "Bangladesh" : "http://www.mohfw.gov.bd/",
  "Aruba" : "https://www.overheid.aw/governance-administration/ministry-of-tourism-public-health-and-sports_3995/",
  "Monaco" : "https://www.gouv.mc/Gouvernement-et-Institutions/Le-Gouvernement/Departement-des-Affaires-Sociales-et-de-la-Sante",
  "Madagascar" : "http://www.sante.gov.mg/",
  "French Guiana" : "https://www.health.gov.gy/",
  "Macao" : "https://www.gov.mo/en/entity-page/entity-552/",
  "Guatemala" : "https://www.mspas.gob.gt/",
  "Jamaica" : "https://www.moh.gov.jm/",
  "French Polynesia" : "https://solidarites-sante.gouv.fr/",
  "Zambia" : "http://www.moh.gov.zm/",
  "Togo" : "https://sante.gouv.tg/",
  "Barbados" : "http://www.health.gov.bb/",
  "Uganda" : "http://health.go.ug/",
  "El Salvador" : "http://www.salud.gob.sv/",
  "Djibouti" : "http://www.sante.gouv.dj/",
  "Mali" : "http://www.sante.gov.ml/",
  "Niger" : "http://www.msp.ne/",
  "Bermuda" : "https://www.gov.bm/ministry/health",
  "Ethiopia" : "http://www.moh.gov.et/ejcc/",
  "Guinea" : "http://sante.gov.gn/",
  "Tanzania" : "http://www.moh.go.tz/",
  "Congo" : "http://www.sante.gouv.cg/",
  "Maldives" : "http://www.health.gov.mv/",
  "Gabon" : "http://www.sante.gouv.ga/",
  "New Caledonia" : "https://dass.gouv.nc/",
  "Myanmar" : "http://www.mohs.gov.mm/",
  "Saint Martin" : "https://solidarites-sante.gouv.fr/",
  "Eritrea" : "https://www.moh.gov.sa/en/Ministry/MediaCenter/News/Pages/NEWS-2011-3-22-002.aspx",
  "Haiti" : "https://mspp.gouv.ht/",
  "Bahamas" : "http://www.bahamas.gov.bs/health",
  "Cayman Islands" : "http://www.gov.ky/portal/page/portal/cighome/find/organisations/azagencies/mhs",
  "Dominica" : "http://dominica.gov.dm/",
  "Equatorial Guinea" : "https://www.guineaecuatorialpress.com/?lang=en",
  "Mongolia" : "http://www.mohs.mn/home",
  "Curaçao" : "https://gobiernu.cw/",
  "Namibia" : "http://www.mhss.gov.na/",
  "Syria" : "http://www.moh.gov.sy/",
  "Greenland" : "https://naalakkersuisut.gl/en/Naalakkersuisut/Departments/Sundhed",
  "Seychelles" : "http://www.gov.sc/GovernmentAgencies/Ministry/minhealth.aspx",
  "Grenada" : "http://health.gov.gd/index.php?lang=en",
  "Laos" : "http://www.moh.gov.la/",
  "Saint Lucia" : "http://health.govt.lc/",
  "Eswatini" : "http://www.gov.sz/index.php/ministries-departments/ministry-of-health",
  "Guyana" : "https://www.health.gov.gy/",
  "Zimbabwe" : "http://www.mohcc.gov.zw/",
  "Guinea-Bissau" : "https://www.developmentaid.org/#!/donors/view/149880/ministry-of-public-health-guinea-bissau",
  "Libya" : "https://www.libyaobserver.ly/ministry-health",
  "Mozambique" : "http://www.misau.gov.mz/",
  "Saint Kitts and Nevis" : "https://www.gov.kn/moh",
  "Suriname" : "http://www.gov.sr/",
  "Angola" : "http://www.minsa.gov.ao/",
  "Sudan" : "http://www.fmoh.gov.sd/",
  "Antigua and Barbuda" : "https://ab.gov.ag/detail_page.php?page=29",
  "Chad" : "https://sante-tchad.org/",
  "Cabo Verde" : "http://www.minsaude.gov.cv/",
  "Mauritania" : "http://www.sante.gov.mr/",
  "Benin" : "https://sante.gouv.bj/",
  "Vatican City" : "http://www.salute.gov.it/portale/home.html",
  "St. Barth" : "https://solidarites-sante.gouv.fr/",
  "Sint Maarten" : "http://www.sintmaartengov.org/government/VSA/Pages/default.aspx",
  "Nepal" : "http://mohp.gov.np/",
  "Fiji" : "http://www.health.gov.fj/",
  "Montserrat" : "http://moh.gov.ms/",
  "Turks and Caicos" : "https://gov.tc/moh/",
  "Gambia" : "http://www.moh.gov.gm/",
  "Nicaragua" : "http://www.minsa.gob.ni/",
  "Bhutan" : "http://www.moh.gov.bt/",
  "Belize" : "http://health.gov.bz/",
  "Botswana" : "https://www.moh.gov.bw/",
  "British Virgin Islands" : "http://www.bvi.gov.vg/content/ministry-health-and-social-development",
  "CAR" : null,
  "Liberia" : "http://moh.gov.lr/",
  "Somalia" : "http://moh.gov.so/en/",
  "MS Zaandam" : null,
  "Anguilla" : "http://gov.ai/ministry.php?id=2",
  "Papua New Guinea" : "http://www.health.gov.pg/",
  "St. Vincent Grenadines" : "http://www.health.gov.vc/health/",
  "Sierra Leone" : "https://mohs.gov.sl/",
  "Timor-Leste" : "http://www.moh.gov.tl/",
  "Burundi" : "http://www.fbpsanteburundi.bi/",
  "China" : "http://www.moh.gov.cn/",
  "Malawi" : "https://www.health.gov.mw/",
  "Falkland Islands" : "https://solidarites-sante.gouv.fr/",
  "Sao Tome and Principe" : "https://www.facebook.com/MSaudeSTeP/"
}